System:

  # Updates can be none (for no update warnings), alpha, beta, and release
  UpdateChannel: release
  Database:
    # Databases Supported:
    # mysql, sqlite

    Type: 'sqlite'
    # [MySQL Default] mysql://localhost:3306/database_name
    URL: 'mysql://localhost:3306/CompleteEconomy'

    # Login details for MySQL database
    Username: ''
    Password: ''